/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#adc6ff',
        secondary: '#d0bcff',
        tertiary: '#4edea3',
        error: '#ffb4ab',
        'primary-container': '#4d8eff',
        'secondary-container': '#571bc1',
        'tertiary-container': '#00a572',
        'error-container': '#93000a',
        'surface-dim': '#0c1324',
        'surface-container-lowest': '#070d1f',
        'surface-container-low': '#151b2d',
        'surface-container': '#191f31',
        'surface-container-high': '#23293c',
        'surface-container-highest': '#2e3447',
        'surface-bright': '#33394c',
        'surface-tint': '#adc6ff',
        'surface-variant': '#2e3447',
        'on-surface': '#dce1fb',
        'on-surface-variant': '#c2c6d6',
        'on-background': '#dce1fb',
        'on-primary': '#002e6a',
        'on-secondary': '#3c0091',
        'on-tertiary': '#003824',
        'on-error': '#690005',
        'on-primary-container': '#00285d',
        'on-secondary-container': '#c4abff',
        'on-tertiary-container': '#00311f',
        'on-error-container': '#ffdad6',
        'inverse-on-surface': '#2a3043',
        'inverse-surface': '#dce1fb',
        'inverse-primary': '#005ac2',
        'outline': '#8c909f',
        'outline-variant': '#424754',
        'primary-fixed': '#d8e2ff',
        'secondary-fixed': '#e9ddff',
        'tertiary-fixed': '#6ffbbe',
        'primary-fixed-dim': '#adc6ff',
        'secondary-fixed-dim': '#d0bcff',
        'tertiary-fixed-dim': '#4edea3',
        'on-primary-fixed': '#001a42',
        'on-secondary-fixed': '#23005c',
        'on-tertiary-fixed': '#002113',
        'on-primary-fixed-variant': '#004395',
        'on-secondary-fixed-variant': '#5516be',
        'on-tertiary-fixed-variant': '#005236',
        background: '#0c1324',
        surface: '#0c1324',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Inter'],
        body: ['Inter'],
        label: ['Inter'],
      },
    },
  },
  plugins: [],
};
