// Material Symbols Icons - using span with class
// To use: <span className="material-symbols-outlined">icon_name</span>

export function LayoutDashboard() { return <span className="material-symbols-outlined">dashboard</span>; }
export function Cpu() { return <span className="material-symbols-outlined">analytics</span>; }
export function FileText() { return <span className="material-symbols-outlined">article</span>; }
export function HealthCheck() { return <span className="material-symbols-outlined">health_and_safety</span>; }
export function Settings() { return <span className="material-symbols-outlined">settings</span>; }

// Additional icons used in components
export function Search() { return <span className="material-symbols-outlined">search</span>; }
export function Notifications() { return <span className="material-symbols-outlined">notifications</span>; }
export function Dns() { return <span className="material-symbols-outlined">dns</span>; }
export function TrendingUp() { return <span className="material-symbols-outlined">trending_up</span>; }
export function TrendingDown() { return <span className="material-symbols-outlined">trending_down</span>; }
export function Schedule() { return <span className="material-symbols-outlined">schedule</span>; }
export function CheckCircle() { return <span className="material-symbols-outlined">check_circle</span>; }
export function Error() { return <span className="material-symbols-outlined">error</span>; }
export function Play() { return <span className="material-symbols-outlined">play_arrow</span>; }
export function Bolt() { return <span className="material-symbols-outlined">bolt</span>; }
export function Rocket() { return <span className="material-symbols-outlined">rocket_launch</span>; }
export function Terminal() { return <span className="material-symbols-outlined">terminal</span>; }
export function Refresh() { return <span className="material-symbols-outlined">refresh</span>; }
export function Delete() { return <span className="material-symbols-outlined">delete_sweep</span>; }
export function Download() { return <span className="material-symbols-outlined">download</span>; }
export function ChevronRight() { return <span className="material-symbols-outlined">chevron_right</span>; }
export function Add() { return <span className="material-symbols-outlined">add</span>; }
export function Filter() { return <span className="material-symbols-outlined">filter_list</span>; }
export function MoreVert() { return <span className="material-symbols-outlined">more_vert</span>; }
export function Calendar() { return <span className="material-symbols-outlined">calendar_today</span>; }
export function Description() { return <span className="material-symbols-outlined">description</span>; }
export function Timer() { return <span className="material-symbols-outlined">timer</span>; }
export function Globe() { return <span className="material-symbols-outlined">globe</span>; }
export function Key() { return <span className="material-symbols-outlined">key</span>; }
export function Save() { return <span className="material-symbols-outlined">save</span>; }
export function Shield() { return <span className="material-symbols-outlined">shield_with_heart</span>; }
export function Verified() { return <span className="material-symbols-outlined">verified</span>; }
export function Hub() { return <span className="material-symbols-outlined">hub</span>; }
export function Database() { return <span className="material-symbols-outlined">database</span>; }
export function Memory() { return <span className="material-symbols-outlined">memory</span>; }
export function SmartToy() { return <span className="material-symbols-outlined">smart_toy</span>; }
export function Monitoring() { return <span className="material-symbols-outlined">monitoring</span>; }
export function ArrowForward() { return <span className="material-symbols-outlined">arrow_forward</span>; }
export function ArrowUp() { return <span className="material-symbols-outlined">arrow_upward</span>; }
export function TaskAlt() { return <span className="material-symbols-outlined">task_alt</span>; }
export function History() { return <span className="material-symbols-outlined">history</span>; }
export function ZonePersonAlert() { return <span className="material-symbols-outlined">zone_person_alert</span>; }
export function Check() { return <span className="material-symbols-outlined">check</span>; }
export function AlertCircle() { return <span className="material-symbols-outlined">error</span>; }
export function Heart() { return <span className="material-symbols-outlined">favorite</span>; }
export function Activity() { return <span className="material-symbols-outlined">activity</span>; }
export function Loader2() { return <span className="material-symbols-outlined">progress_activity</span>; }
export function FileX() { return <span className="material-symbols-outlined">file_delete</span>; }
export function Cog() { return <span className="material-symbols-outlined">settings</span>; }
export function Server() { return <span className="material-symbols-outlined">dns</span>; }
export function Zap() { return <span className="material-symbols-outlined">bolt</span>; }
export function EditNote() { return <span className="material-symbols-outlined">edit_note</span>; }
export function Share() { return <span className="material-symbols-outlined">share</span>; }
